# Generated by Django 2.2.1 on 2020-07-15 10:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200715_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='create_date',
        ),
        migrations.AddField(
            model_name='post',
            name='created_date',
            field=models.TimeField(default=datetime.datetime(2020, 7, 15, 10, 34, 48, 801943, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 15, 10, 34, 48, 801943, tzinfo=utc)),
        ),
    ]
